[build]
    command = "npm run build"
    publish = "_site"
[context.production]
    command = "JEKYLL_ENV=production npm run build"
[[redirects]]
    from = "https://sg-design-system.netlify.com/*"
    to = "https://www.designsystem.gov.sg/:splat"
    status = 301
    force = true